name: Build PipeWire with AAC Codec

on:
  create:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }} 
    outputs:
      build_matrix: ${{ steps.matrix_setup.outputs.build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: matrix_setup
        run: |
          # PACKAGES=$(ls -d ${{ github.workspace }}/packages/* | xargs -n 1 basename | jq -R . | jq -s .)
          # DISTS=$(echo debian:{sid,bookworm}-slim | jq -R 'split(" ")')
          # ARCHS=$(echo amd64 arm64 | jq -R 'split(" ")')

          PACKAGES=$(echo pipewire | jq -R 'split(" ")')
          DISTS=$(echo debian:sid-slim | jq -R 'split(" ")')
          ARCHS=$(echo amd64 | jq -R 'split(" ")')
          echo "build=$(
            jq -cn --argjson p "$PACKAGES" \
                   --argjson d "$DISTS" \
                   --argjson a "$ARCHS" \
              '{package:$p,"os-version":$d,arch:$a}'
          )" >> $GITHUB_OUTPUT
      

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.build_matrix) }}
    steps:
      # - name: Set up environment
      #   run: |
      #     if [ -f /etc/apt/sources.list.d/debian.sources ]; then
      #         sed -i '/^Types:/ s/$/ deb-src/' /etc/apt/sources.list.d/debian.sources
      #         cat /etc/apt/sources.list.d/debian.sources
      #     else
      #         echo "deb-src https://deb.debian.org/debian/ sid main" | tee /etc/apt/sources.list
      #         cat /etc/apt/sources.list

      #     fi
      #     apt-get update
      #     # apt-get install -y build-essential devscripts debhelper dh-make

      # - name: Download PipeWire Source
      #   run: |
      #     apt-get source pipewire
      #     cd pipewire-*  # Change to the downloaded source directory
      #     echo "bluez5-codec-aac=enabled" >> debian/flags
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.package }} Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "${{ matrix.os-version }}"
          host-arch: "${{ matrix.arch }}"
          source-dir: "build/${{ matrix.package }}"
          setup-hook: |
            set -v
            if [ -f /etc/apt/sources.list.d/debian.sources ]; then
                sed -i '/^Types:/ s/$/ deb-src/' /etc/apt/sources.list.d/debian.sources
                cat /etc/apt/sources.list.d/debian.sources
            else
                echo "deb-src https://deb.debian.org/debian/ sid main" | tee /etc/apt/sources.list
                cat /etc/apt/sources.list
            fi
            cd $GITHUB_WORKSPACE
            apt-get -qq update
            apt-get -qq install -y devscripts wget #build-essential  debhelper dh-make
            bash check-dsc.sh ${{ matrix.package }} ./packages ./build

            # DEB_VERSION=$(apt-cache madison ${{ matrix.package }} | awk '{print $3}')
            # DEB_VERSION=$(awk '/^Version: /{print $2}' ./build/)
            # VERSION=$(echo $DEB_VERSION | cut -d'-' -f1)

            DEB_VERSION=1.4.1-1
            VERSION=$(echo $DEB_VERSION | cut -d'-' -f1)        

            # echo "DEB_VERSION: $DEB_VERSION"
            # echo "VERSION: $VERSION"

            # export INPUT_SOURCE_DIR="$PWD/${{ matrix.package }}-$VERSION"

            mv -v ./build/${{ matrix.package }}-$VERSION/ ./build/${{ matrix.package }}
            # apt build-dep -y ${{ matrix.package }}

            # apt-get source pipewire
            # cd pipewire-*  # Change to the downloaded source directory
            # echo "bluez5-codec-aac=enabled" >> debian/flags
          extra-build-deps: devscripts git dpkg-cross
          # before-build-hook: "dch --local ~${{ github.run_number }} 'GitHub build for PipeWire with AAC Codec'"rw
          buildpackage-opts: --build=binary --no-sign -d
        
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.package }}-${{ matrix.arch }}"
          path: ./debian/artifacts/*

  merge-artefacts:
    name: Merge all deb files to single artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge debian packages
        uses: actions/upload-artifact/merge@v4

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    name: Add packages to public Debian repository
    runs-on: ubuntu-latest
    needs: merge-artefacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "merged-artifacts"
      - name: Add releases to repo
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
            arm64
          repo_supported_version: |
            sid
            bookworm
          file: |
            *.deb
          version_by_filename: true
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          public_key: ${{ vars.APT_PUBLIC_KEY }}
          key_passphrase: ""
          skip_duplicates: true
