name: Build Debian Packages

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.dataStep.outputs.myoutput }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}  # Set default working directory to root
    steps:
      - id: dataStep
        run: |
          TARGETS=$(ls -d ${{ github.workspace }}/packages/* | xargs -n 1 basename | jq -R . | jq -s .)
          echo "myoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}  # Set default working directory to root
    steps:
      - run: echo ${{ matrix.target }}
