name: Build Debian Packages

on:
  push:
    branches:
      - main

jobs:
  list-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List package directories
        id: set-packages
        run: |
          # List directories in 'sources/' that contain a 'debian' directory
          # packages=$(find sources -mindepth 1 -maxdepth 1 -type d -exec test -d '{}/debian' \; -print | sed 's|sources/||' | tr '\n' ',' | sed 's/,$//')
          # echo "packages=${packages}" >> $GITHUB_ENV
          echo "package=$(ls -d packages/* | xargs -n 1 basename | jq -R . | jq -s .)" >> $GITHUB_ENV
          echo "::set-output name=packages::${packages}"

  build:
    runs-on: ubuntu-latest
    needs: list-packages
    strategy:
      matrix:
        package: ${{ fromJson(needs.list-packages.outputs.packages) }}

    steps:
      - name: Print package name
        run: |
          echo "Package: ${{ matrix.package }}"
